name: Test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  python:
    name: ${{ matrix.os_short }} python
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022", "macos-15", "ubuntu-22.04"]
        include:
          - os: "windows-2022"
            os_short: "windows"
          - os: "macos-15"
            os_short: "macos"
            cmake_generator: "Unix Makefiles"
          - os: "ubuntu-22.04"
            os_short: "linux"
            cmake_generator: "Unix Makefiles"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: prepare
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            version="${GITHUB_REF##*/}"
          else
            version="$(date '+%Y.%-m.%-d').dev${GITHUB_RUN_NUMBER}"
          fi
          sed -i.bak "s/^version = .*/version = \"${version}\"/g" pyproject.toml && rm pyproject.toml.bak
          echo "${version}" > src/git-tag.txt
          
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install
        shell: bash
        run: |
          if [ "${{ matrix.os_short }}" == "linux" ]; then
            export OCL_INSTALL_BOOST="1"
            export OCL_BOOST_PREFIX="$(pwd)"
            export PIP_CACHE_DIR=$HOME/wheelhouse
          else
            export OCL_INSTALL_BOOST_FROM_REPO="1"
          fi
          ./install.sh \
            --build-library python \
            --build-type release \
            --install-system-deps \
            --python-executable python \
            --python-pip-install \
            --test
        env:
          CMAKE_GENERATOR: ${{ matrix.cmake_generator }}
      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os_short }}-python-${{ matrix.architecture }}
          path: |
            $HOME/wheelhouse/*.whl
      - uses: actions/download-artifact@v6
        with:
          path: prebuilds
